### ISSUE TITLE
Enable translations using gettext

### ISSUE THREAD

**Issue by activityworkshop** [geopython/mapslicer#14]
Hi,
I'm really sorry but it looks like that last change you merged from me has got a problem with it.  All the translations work fine, but then (for some mysterious reason) either gdal or pp has a problem with importing the mapslicer module(?) and the rendering fails.

I cannot fathom what the problem is, and the only way I can get it to run is to prevent wizard.py from using gettext.  So some of the texts are translated (by config, main, widgets) and some not (by wizard), but at least gdal and pp are then happy - I have _no_ idea why.

So you have two choices - either you take my following commit which prevents wizard.py from using gettext, or you go back to the previous version and take out all the gettext stuff.  Whichever you prefer.
Again, sorry!

**Comment by kalxas** [comment]
no worries, we can easily revert and keep the gettext code in a branch until it is solved

**Comment by kalxas** [comment]
Actually the solution you offer is better because it will keep the good changes you did

**Comment by kalxas** [comment]
I have created a branch to work on this issue:
https://github.com/kalxas/mapslicer/tree/14-translations

**Comment by activityworkshop** [comment]
I tried to create a pull request for you, for my commit 5be0d70e7d but I can't get it to work.  When I select that commit it shows me the differences from your 14-translations branch, which are ok, but then there's no green button to submit a pull request any more.  I guess it should be really easy but I can't see it.

**Comment by kalxas** [comment]
I fetched your changes and merged in 14-translations branch. No conflict.

**Comment by activityworkshop** [comment]
I'll close this issue then, we can figure out a more complete solution after the release, if that's ok with you.

**Comment by kalxas** [comment]
Thanks!
