### ISSUE TITLE
Exception occured when trying to render

### ISSUE THREAD

**Issue by arsenalol69** [geopython/mapslicer#19]
Hi ! First, thanks for your work, it's just great ! 

I'm trying to use MapSlicer on Windows but It doesn't work : when I try to render, I have an exeption :

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\XXX\mapslicer-master\mapslicer\main.py", line 372, in _resultConsumer
    raise self.g2t
error: unpack requires a string argument of length 8

Thanks in advance for your help.

**Comment by kalxas** [comment]
Actually I don't remember to have tested against wx 3.x
Can you please try against wx 2.x?

**Comment by arsenalol69** [comment]
Ok I will try ! Thanks !

**Comment by arsenalol69** [comment]
I've got the same exception : File "C:\Python27\lib\site-packages\wx-2.9.5-msw\wx\_core.py", line 16767, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\XXX\mapslicer-master\mapslicer\main.py", line 372, in _resultConsumer
    raise self.g2t
error: unpack requires a string argument of length 8

I also have a warning at the beginning : Warning (from warnings module):
  File "C:\Users\hassendal\Desktop\mapslicer-master\mapslicer.py", line 55
    wx.InitAllImageHandlers()
wxPyDeprecationWarning: Call to deprecated item 'InitAllImageHandlers'. 

I'm trying to install OSGeo too. I think that it should be easier to use it.

**Comment by arsenalol69** [comment]
I successfully installed OSGeo with the ISO file. MapSlicer works really well ! Thanks for you time and for your great job !
