### ISSUE TITLE
XYZ/WMTS support

### ISSUE THREAD

**Issue by webmap2015** [geopython/mapslicer#20]
Could you add TMS with inverted y-axis ?

Here is example:
"https://github.com/pramsey/gdal2tilesp".

Thanks.

**Comment by kevinworthington** [comment]
I've been testing out this feature and have noticed that maps which cross the prime meridian are off longitudinally when generating tiles in XYZ. Here's a geotiff which demonstrates with http://maps.scholarsportal.info/files/zips/OpenContent/WWIIMM/WWIIMMCaen_1944_TIFF.zip
Can you let me know what I can do to fix this?
