### ISSUE TITLE
Update overview and quickstart in OSGeoLive documentation

### ISSUE THREAD

**Issue by kalxas** [geopython/mapslicer#7]

**Comment by kalxas** [comment]
http://adhoc.osgeo.osuosl.org/livedvd/docs/en/overview/mapslicer_overview.html
http://adhoc.osgeo.osuosl.org/livedvd/docs/en/quickstart/mapslicer_quickstart.html

Done :)

**Comment by johanvdw** [comment]
Just wondering: can we use the currently used logo?

**Comment by kalxas** [comment]
The icon.png was released under BSD, it is out there already ;)

**Comment by activityworkshop** [comment]
Nice job on the doc pages, that was fast!
